protected/controllers/NewsController.php
<?php

class NewsController extends Controller
{

    public function actionIndex()
    {
        $articles = Article::model()->findAll(array('limit' => 10));
        
        $this->render('index', array('articles' => $articles));
    }

    
    public function actionView($id)
    {
        $article = Article::model()->findByPk((int) $id);
        
        if(!($article instanceof Article)) {
            throw new CHttpException(404, 'Article not found');
        }
        
        $this->render('view', array('article' => $article));
    }
    
    public function actionByKeyword($id)
    {
        $keyword = Keyword::model()->findByPk((int) $id);
        
        if(!($keyword instanceof Keyword)) {
            throw new CHttpException('Keyword not found');
        }
        
        $this->render('byKeyword', array('keyword' => $keyword, 'articles' => $keyword->articles));
    }

}

protected/views/news/_articles.php
<?php

?>

<?php foreach ($articles as /* @var $article Article */ $article) { ?>
<div>
    <a href="<?php echo Yii::app()->urlManager->createUrl('/news/view', array('id' => $article->id)) ?>"><?php echo CHtml::encode($article->title); ?></a>
    <p>
        <?php echo mb_substr($article->text, 0, 100); ?>
    </p>
</div>
<?php } ?>

protected/views/news/byKeyword.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>

<h1>News with "<?php echo $keyword->name; ?>" keyword</h1>


<?php $this->renderPartial('_articles', array('articles' => $articles)); ?>

protected/views/news/index.php
<?php

/* @var $this Controller */


?>

<?php $this->renderPartial('_articles', array('articles' => $articles)); ?>

protected/views/news/view.php
<?php

/* @var $article Article */

?>

<h1><?php echo CHtml::encode($article->title); ?></h1>

<p><?php echo nl2br(CHtml::encode($article->text)); ?></p>

<?php if($article->category) { ?>
<div>
    Category: <?php echo $article->category->title; ?>
</div>
<?php } ?>
<div>
    User: 
</div>
<?php if($article->tags) { ?>
    Tags: 
    <?php foreach ($article->tags as /* @var $keyword Keyword */ $keyword) { ?>
        <?php echo CHtml::link($keyword->name, array('news/byKeyword', 'id' => $keyword->id)); ?> 
    <?php } ?>
<?php } ?>